### ISSUE TITLE
pattern not match with data

### ISSUE THREAD

**Issue by tomqwu** [oosidat/fluentd-elasticsearch-container#1] opened 2016-01-29 14:27 UTC
I quickly tested the filter, however I am getting pattern not match with data,

```
<source>
  @type forward
</source>

<filter **>
    type parser
    format json_in_string
    time_format %Y-%m-%d %H:%M:%S %L
    key_name log
    hash_value_field log
</filter>

<match **>
  @type copy
  <store>
    type elasticsearch
    host localhost
    port 9200
    include_tag_key true
    tag_key @log_name
    logstash_format true
    flush_interval 10s
  </store>
  <store>
    @type stdout
  </store>
</match>
```

here is a quickly docker run to stdout a JSON as string

```
docker run --log-driver=fluentd ubuntu /bin/echo '{"key":"value"}'
```

Without the parser, it looks like

```
2016-01-29 14:31:03 +0000 docker.2b2e76f81e93: {"container_id":"2b2e76f81e93bb582d7264bad19edb62a4aadede77684e71d3052acabcbfe254","container_name":"/clever_darwin","source":"stdout","log":"{\"key\":\"value\"}","@log_name":"docker.2b2e76f81e93"}
```

```
2016-01-29 13:58:54 +0000 [warn]: pattern not match with data '{"key":"value"}'
```

**Comment by oosidat** [comment] 2016-01-29 15:27
If you're using my conf file as is, you'll get a `pattern not match` for any logs without a tag matching `docker.**`. For some reason, `<match **>` didn't work for my case.

Also, I haven't tested it with other conf files (or other inputs other than docker containers logging it via the fluentd logdriver) - feel free to fork, fix for your use case, and submit a PR if appropriate.

**Comment by tbenade** [comment] 2016-02-09 06:07
Hi Osama as @canadatom mentioned we have the same behaviour with our own containers but also when using yours unchanged. Just want to confirm if this ever worked or is still working for you?

Thanks sir.

**Comment by oosidat** [comment] 2016-02-09 17:17
This is working for me currently, however, you might want to check out v1.0.0 - in particular, commit cfe4dee4d3fc765590327af6c69ce8f2f9c541c5. This issue may have been fixed as a result of that.

If I get time today, I'll run the above test case and report back.

Protip: specify environment variable FLUENTD_OPT=-vv to get a bit more verbose output from fluentd.

**Comment by tbenade** [comment] 2016-02-09 19:08
Thanks, really appreciate you taking the time. Looks like 1.0 wont be working for us either. Reason being we don't have any time data appended to the event being emmited by the docker log driver. This means no matter what the Paser plugin keeps telling no match for pattern and data. So wondering how are you get time data into the events emmitted by the logging driver? Thanks.

**Comment by oosidat** [comment] 2016-02-10 03:42
From [Fluent docs](http://www.fluentd.org/guides/recipes/docker-logging)

> ... the incoming messages have a timestamp, are tagged with the container_id and contains general information from the source container along the message, everything in JSON format.

I'm using this container in a scenario where logs are forwarded by two sources:
- docker containers where logging driver set to fluent 
- development environments where a bunyan logger is used with fluent streams ([bunyan adds time to the logs](https://github.com/trentm/node-bunyan#introduction))

I think we could work around the problem you're seeing by modifying the plugin by checking if hash['time'] is nil, and if it is, setting it to `Time.now.some_format`.

I'm attempting to reproduce the problem as specified in the first comment - if I have any luck I'll post here (and possibly point you to the branch I made my changes in).

**Comment by oosidat** [comment] 2016-02-10 04:56
So, I made some updates to the plugin regarding the time value and tested it with the following (with a slightly modified fluent configuration):
- Run fluent container:

```
$ docker run -d --net=host -e FLUENTD_OPT=-vv --name flu customflu
```
- Run ubuntu image from above:

```
$ docker run -d --net=host --log-driver=fluentd ubuntu /bin/echo '{"key":"value"}'
```
- Get logs from fluent container

```
$ docker logs -f flu
```

Output:

```
...
2016-02-10 04:42:54 +0000 [info]: fluent/engine.rb:121:configure: using configuration file: <ROOT>
  <source>
    type forward
  </source>
  <filter docker.**>
    type parser
    format json_in_string
    time_format %Y-%m-%dT%H:%M:%S.%L%Z
    key_name log
    hash_value_field log
  </filter>
  <match docker.**>
    type copy
    <store>
      type stdout
    </store>
  </match>
</ROOT>
2016-02-10 04:42:54 +0000 [info]: plugin/in_forward.rb:81:listen: listening fluent socket on 0.0.0.0:24224
2016-02-10 04:42:57 +0000 [trace]: plugin/in_forward.rb:227:initialize: accepted fluent socket from '127.0.0.1:54440': object_id=47005657052780
2016-02-10 04:42:57 +0000 docker.78f3b7391e8e: {"log":{"key":"value"}}
2016-02-10 04:42:57 +0000 [trace]: plugin/in_forward.rb:295:on_close: closed socket
...
```

The change is on the [dev branch](https://github.com/oosidat/fluentd-elasticsearch-container/tree/dev) which corresponds to the [experimental](https://hub.docker.com/r/oosidat/fluentd-elasticsearch-container/builds/be3azppj9jlmsknjeynqijf/) tag on docker hub.

@canadatom @tbenade Please let me know if this resolves your problem.

**Comment by MrMMorris** [comment] 2016-05-04 16:12
Thanks for taking the time to make this.

@oosidat just to make sure, this should work with logs that don't have a timestamp? It will add one if missing?

Here is what I am getting:

```
Initialized plugin setup
Finished setting up plugins on file /fluentd/etc/fluent.conf
2016-05-04 16:00:22 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-05-04 16:00:22 +0000 [info]: starting fluentd-0.12.23
2016-05-04 16:00:22 +0000 [info]: gem 'fluent-plugin-color-stripper' version '0.0.3'
2016-05-04 16:00:22 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.4.0'
2016-05-04 16:00:22 +0000 [info]: gem 'fluent-plugin-parser' version '0.6.1'
2016-05-04 16:00:22 +0000 [info]: gem 'fluentd' version '0.12.23'
2016-05-04 16:00:22 +0000 [info]: adding filter pattern="docker.**" type="parser"
2016-05-04 16:00:22 +0000 [info]: adding match pattern="docker.**" type="copy"
2016-05-04 16:00:23 +0000 [info]: adding match pattern="**" type="stdout"
2016-05-04 16:00:23 +0000 [info]: adding source type="forward"
2016-05-04 16:00:23 +0000 [info]: using configuration file: <ROOT>
  <source>
    type forward
  </source>
  <filter docker.**>
    type parser
    format json_in_string
    time_format %Y-%m-%dT%H:%M:%S.%L%Z
    key_name log
    hash_value_field log
  </filter>
  <match docker.**>
    type copy
    <store>
      type elasticsearch
      logstash_format true
      hosts csm-elasticsearch-dev-1.node.consul,csm-elasticsearch-dev-2.node.consul,csm-elasticsearch-dev-3.node.consul
      port 9200
      index_name fluentd
      type_name fluentd
      include_tag_key true
    </store>
  </match>
  <match **>
    type stdout
  </match>
</ROOT>
2016-05-04 16:00:23 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2016-05-04 16:07:25 +0000 [warn]: pattern not match with data 'info: updated content collection for node 1cf916d8-4b1c-40f6-bb85-bde4f026638a'
```

This is using the json_in_string plugin on the dev branch

**Comment by oosidat** [comment] 2016-05-04 17:29
@MrMMorris I think the updated `json_in_string` plugin should handle missing timestamps - however, in your case, I think it's the format of the log that may be the problem - it's expecting a log message in a key-value format - maybe something like: 

```
{"info": "updated content collection for node 1cf916d8-4b1c-40f6-bb85-bde4f026638a"}
```

I still think it still should have been caught by the last catch-all match tag and output to stdout... not sure why that doesn't seem to be happening here...

Do you have a test case that I can use?

**Comment by zerthimon** [comment] 2016-10-05 18:32
Also having the same problem with your container:
I'm running it with:

```
docker run -d --name fluentd-forwarder -e ES_HOST=10.10.1.1 -e FLUENTD_OPT=-vv --net=host oosidat/fluentd-elasticsearch-container
```

This is what's in logs

```
Initialized plugin setup
Finished setting up plugins on file /fluentd/etc/fluent.conf
2016-10-05 18:09:33 +0000 [info]: fluent/supervisor.rb:457:read_config: reading config file path="/fluentd/etc/fluent.conf"
2016-10-05 18:09:33 +0000 [info]: fluent/supervisor.rb:323:supervise: starting fluentd-0.12.20
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered buffer plugin 'file'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered buffer plugin 'memory'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered filter plugin 'grep'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered filter plugin 'record_transformer'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered filter plugin 'stdout'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'debug_agent'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'dummy'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'exec'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'forward'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'gc_stat'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'http'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'monitor_agent'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'object_space'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'status'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'unix'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'syslog'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'tail'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'tcp'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered input plugin 'udp'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'copy'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'exec'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'exec_filter'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'file'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'forward'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'null'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'relabel'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'roundrobin'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'stdout'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'tcp'
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'unix'
2016-10-05 18:09:33 +0000 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-elasticsearch' version '1.3.0'
2016-10-05 18:09:33 +0000 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-parser' version '0.6.0'
2016-10-05 18:09:33 +0000 [info]: fluent/engine.rb:114:block in configure: gem 'fluentd' version '0.12.20'
2016-10-05 18:09:33 +0000 [info]: fluent/agent.rb:137:add_filter: adding filter pattern="docker.**" type="parser"
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered filter plugin 'parser'
2016-10-05 18:09:33 +0000 [info]: fluent/agent.rb:125:add_match: adding match pattern="docker.**" type="elasticsearch"
2016-10-05 18:09:33 +0000 [trace]: fluent/plugin.rb:118:register_impl: registered output plugin 'elasticsearch'
2016-10-05 18:09:33 +0000 [info]: fluent/agent.rb:125:add_match: adding match pattern="**" type="stdout"
2016-10-05 18:09:33 +0000 [info]: fluent/root_agent.rb:143:add_source: adding source type="forward"
2016-10-05 18:09:33 +0000 [info]: fluent/engine.rb:121:configure: using configuration file: <ROOT>
  <source>
    type forward
  </source>
  <filter docker.**>
    type parser
    format json_in_string
    time_format %Y-%m-%dT%H:%M:%S.%L%Z
    key_name log
    hash_value_field log
  </filter>
  <match docker.**>
    type elasticsearch
    logstash_format true
    host 10.10.1.1
    port 9200
    index_name fluentd
    type_name fluentd
    include_tag_key true
  </match>
  <match **>
    type stdout
  </match>
</ROOT>
2016-10-05 18:09:33 +0000 [info]: plugin/in_forward.rb:81:listen: listening fluent socket on 0.0.0.0:24224
```

So, when I do:

```
docker run --log-driver=fluentd ubuntu /bin/echo '{"key":"value"}'
```

I get:

```
2016-10-05 18:30:34 +0000 [info]: plugin/in_forward.rb:81:listen: listening fluent socket on 0.0.0.0:24224
2016-10-05 18:31:05 +0000 [trace]: plugin/in_forward.rb:227:initialize: accepted fluent socket from '127.0.0.1:24810': object_id=47121936425620
2016-10-05 18:31:05 +0000 [warn]: plugin/filter_parser.rb:46:block (2 levels) in filter_stream: pattern not match with data '{"key":"value"}'
2016-10-05 18:31:05 +0000 [trace]: plugin/in_forward.rb:295:on_close: closed socket
2016-10-05 18:31:05 +0000 fluent.trace: {"message":"accepted fluent socket from '127.0.0.1:24810': object_id=47121936425620"}
2016-10-05 18:31:05 +0000 fluent.warn: {"message":"pattern not match with data '{\"key\":\"value\"}'"}
2016-10-05 18:31:05 +0000 fluent.trace: {"message":"closed socket"}
```

**Comment by oosidat** [comment] 2016-10-05 19:41
Try using the `experimental` image instead - I made a few fixes there

See: https://github.com/oosidat/fluentd-elasticsearch-container/issues/1#issuecomment-182200017

Unfortunately I'm not actively working on this these days - I welcome any PRs if they help resolve general issues.

**Comment by zerthimon** [comment] 2016-10-06 12:36
@oosidat 
The experimental image works like a charm. Why not merging it into a stable one ?

**Comment by oosidat** [comment] 2016-10-06 15:49
I'll look into it - my old team had a use case for the previous image last I checked - don't wanna break 'em!

**Comment by oosidat** [comment] 2017-06-14 02:00
I merged the `dev` branch into `master` sometime last year - that should have taken care of any issues in this thread. Closing this; if you have an issue/wish to have a discussion about this, please create a new issue (bear in mind that I haven't worked on this for a while now).

**Closed as completed by oosidat** 2017-06-14 02:00 UTC
